import type { DesignDirection } from "@/domain/design/design-direction";

// Design Directions je Küche (ROADMAP Stufe 3, ADR 0019). Jede ist ein Startpunkt, keine Vorlage.
// Referenzen stammen aus dem v2-Referenzkatalog (gastro-webagentur @bd23138, v2/designsysteme/*.md).
// Keine davon wurde bisher von Hand auf der Website geprüft – deshalb `verified: false`.

const V2 = (file: string) => `gastro-webagentur v2/designsysteme/${file}.md`;

export const DIRECTIONS = [
  {
    id: "wirtshaus-stadtplatz",
    name: "Wirtshaus am Stadtplatz",
    mood: "Papier, Wirtshausgrün und eine Karte, die sich wie die Tafel im Gastraum liest.",
    cuisines: ["bayerisch"],
    references: [
      { name: "Augustiner Klosterwirt", url: "https://www.augustiner-klosterwirt.de", kind: "restaurant", adopted: ["warmer, heller Grund", "Serifen-Überschriften in normaler Schreibweise", "Speisekarte als ruhige Liste"], rejected: ["Bildslider mit Autoplay"], verified: false, foundIn: V2("bayerisch--wirtshaus") },
      { name: "Ayingers Wirtshaus", url: "https://www.ayingers.de", kind: "restaurant", adopted: ["Grün als Hausfarbe"], rejected: ["Navigation mit vielen Ebenen"], verified: false, foundIn: V2("bayerisch--wirtshaus") },
      { name: "Raus", url: "https://styles.refero.design/style/d28732de-1b7a-4d37-b7aa-edfa7caf428b", kind: "design", adopted: ["Cream-Papier und fast schwarze Tinte", "ein Grün als Signal"], rejected: ["technische Grotesk als Textschrift"], verified: false, foundIn: V2("bayerisch--wirtshaus") },
    ],
    typography: { display: "vollkorn", displayWeight: 700, body: "alegreya-sans", scale: "editorial", labelCase: "normal" },
    palette: { background: "#f7f2e7", surface: "#fffdf8", text: "#1f2a22", textMuted: "#55604e", primary: "#24553a", onPrimary: "#ffffff", accent: "#a87a2a", line: "#e3dccb" },
    shape: { radius: "none" },
    layout: { hero: "split-editorial", menu: "typographic", gallery: "masonry" },
    motion: { intensity: "quiet" },
  },
  {
    id: "trattoria-kochbuch",
    name: "Trattoria wie ein Kochbuch",
    mood: "Cremefarbenes Papier, rotbraune Tinte, die Karte in Gängen gesetzt wie in einem Kochbuch.",
    cuisines: ["italienisch"],
    references: [
      { name: "Bocca di Lupo", url: "https://www.boccadilupo.com", kind: "restaurant", adopted: ["Karte als lange, gut gesetzte Liste", "warmer Grund"], rejected: ["kleine Schrift in der Karte"], verified: false, foundIn: V2("italienisch--trattoria") },
      { name: "Padella", url: "https://www.padella.co", kind: "restaurant", adopted: ["wenige, klare Wege"], rejected: ["schwarzer Vollflächen-Grund"], verified: false, foundIn: V2("italienisch--trattoria") },
      { name: "Alison Roman", url: "https://styles.refero.design/style/b2ace2c1-d6ee-4d57-915e-901224cded11", kind: "design", adopted: ["Cream-Papier", "tiefes Rotbraun als Tinte", "Serifen-Überschriften"], rejected: ["Systemschrift als Text"], verified: false, foundIn: V2("italienisch--trattoria") },
    ],
    typography: { display: "cormorant-garamond", displayWeight: 600, body: "karla", scale: "editorial", labelCase: "normal" },
    palette: { background: "#fbf6ee", surface: "#fffdf9", text: "#2a211a", textMuted: "#66584b", primary: "#8f3418", onPrimary: "#ffffff", accent: "#ad7d28", line: "#eadfce" },
    shape: { radius: "none" },
    layout: { hero: "immersive-type", menu: "course-led", gallery: "full-bleed" },
    motion: { intensity: "editorial" },
  },
  {
    id: "taverne-am-hafen",
    name: "Taverne am Hafen",
    mood: "Kalkstein und Tiefseeblau, Meze als kleine Zettel mit Preis, der Tagesfang vorn.",
    cuisines: ["griechisch"],
    references: [
      { name: "Taverna Kyclades", url: "https://www.tavernakyclades.com", kind: "restaurant", adopted: ["Blau als Hausfarbe", "Tagesfang als Thema"], rejected: ["Mäander-Ornamente"], verified: false, foundIn: V2("griechisch--taverne-am-hafen") },
      { name: "The Real Greek", url: "https://www.therealgreek.com", kind: "restaurant", adopted: ["Meze als Raster aus Name und Preis", "heller Grund"], rejected: ["Aktions-Banner"], verified: false, foundIn: V2("griechisch--taverne-am-hafen") },
      { name: "Relief", url: "https://styles.refero.design/style/e6b53c1e-644b-4300-b42f-0e64905d1443", kind: "design", adopted: ["ruhige, helle Flächen"], rejected: ["generische Geometrie-Grotesk"], verified: false, foundIn: V2("griechisch--taverne-am-hafen") },
    ],
    typography: { display: "marcellus", displayWeight: 400, body: "figtree", scale: "editorial", labelCase: "uppercase" },
    palette: { background: "#f4f2ec", surface: "#fdfcf9", text: "#17232c", textMuted: "#4f5b63", primary: "#1d4f73", onPrimary: "#ffffff", accent: "#62839b", line: "#dfdcd2" },
    shape: { radius: "soft" },
    layout: { hero: "split-editorial", menu: "card-minimal", gallery: "horizontal-scroll" },
    motion: { intensity: "quiet" },
  },
  {
    id: "grillhaus-tafel",
    name: "Grillhaus mit Plakatschrift",
    mood: "Ein einziges lautes Rot auf warmem Ton, die Karte wie die Tafel über dem Holzkohlegrill.",
    cuisines: ["tuerkisch"],
    references: [
      { name: "Karaköy Lokantası", url: "https://www.karakoylokantasi.com", kind: "restaurant", adopted: ["Karte als Tafel", "Sandtöne"], rejected: ["Sprachwahl als Hauptelement"], verified: false, foundIn: V2("tuerkisch--basar") },
      { name: "VALIENTE BRANDS", url: "https://styles.refero.design/style/f63bf016-5b53-4ddf-9f8c-da43f75a9e2b", kind: "design", adopted: ["ein einziges lautes Rot", "warmer Tongrund", "monolithische Grotesk"], rejected: ["Pfirsich-Vollfläche"], verified: false, foundIn: V2("tuerkisch--basar") },
      { name: "Roberta's Pizza", url: "https://styles.refero.design/style/3e497155-bd96-4134-a4a5-855bd885a25c", kind: "design", adopted: ["Plakat-Hierarchie"], rejected: ["Karo-Muster"], verified: false, foundIn: V2("tuerkisch--basar") },
    ],
    typography: { display: "bricolage-grotesque", displayWeight: 800, body: "work-sans", scale: "monumental", labelCase: "uppercase" },
    palette: { background: "#f3e7d8", surface: "#fbf4ea", text: "#231a14", textMuted: "#5c4b3e", primary: "#b3261e", onPrimary: "#ffffff", accent: "#8a5a2b", line: "#e2d2bf" },
    shape: { radius: "none" },
    layout: { hero: "immersive-type", menu: "typographic", gallery: "full-bleed" },
    motion: { intensity: "expressive" },
  },
  {
    id: "damaszener-hof",
    name: "Damaszener Hof",
    mood: "Petrol und Creme wie Kacheln im Innenhof, die Geschichte des Hauses vor der Karte.",
    cuisines: ["syrisch"],
    references: [
      { name: "Malakeh", url: "https://www.malakeh.de", kind: "restaurant", adopted: ["Hausgeschichte weit vorn"], rejected: ["Stockfotos"], verified: false, foundIn: V2("syrisch--damaszener-hof") },
      { name: "Lawrence Berlin", url: "https://lawrence.berlin/en/arabic-restaurant/", kind: "restaurant", adopted: ["Mezze-Karte klar gegliedert", "gedeckte Töne"], rejected: ["Event-Buchung im Vordergrund"], verified: false, foundIn: V2("syrisch--damaszener-hof") },
      { name: "OLIPOP", url: "https://styles.refero.design/style/c6ec55c7-0bd9-47c5-a4d2-669b7790c9cc", kind: "design", adopted: ["Waldpetrol und Creme", "Menü-Karten-Anmutung"], rejected: ["Soda-Bildsprache"], verified: false, foundIn: V2("syrisch--damaszener-hof") },
    ],
    typography: { display: "reem-kufi", displayWeight: 600, body: "alegreya-sans", scale: "editorial", labelCase: "normal" },
    palette: { background: "#f5f0e4", surface: "#fcf9f2", text: "#1b2b2b", textMuted: "#4d5b59", primary: "#1f5c5a", onPrimary: "#ffffff", accent: "#a8612b", line: "#e0d9c8" },
    shape: { radius: "soft" },
    layout: { hero: "split-editorial", menu: "card-minimal", gallery: "masonry" },
    motion: { intensity: "quiet" },
  },
  {
    id: "nudelhaus-nacht",
    name: "Nudelhaus bei Nacht",
    mood: "Lackschwarz mit einem einzigen Rot, die Karte in Gängen wie eine Bestellkarte zum Ankreuzen.",
    cuisines: ["chinesisch"],
    references: [
      { name: "Hakkasan", url: "https://hakkasan.com", kind: "restaurant", adopted: ["Schwarzgrund", "sparsamer roter Akzent"], rejected: ["Club- und Event-Fokus"], verified: false, foundIn: V2("chinesisch--shanghai-nacht") },
      { name: "Mott 32", url: "https://www.mott32.com", kind: "restaurant", adopted: ["reduzierte Typografie"], rejected: ["Standortwahl vor Inhalt"], verified: false, foundIn: V2("chinesisch--shanghai-nacht") },
      { name: "Freshman", url: "https://styles.refero.design/style/a6284fcd-fa69-4469-ac40-4239e5b84a39", kind: "design", adopted: ["Titelkarten-Typografie", "Rot als einziger Akzent"], rejected: ["Kinofilm-Layout"], verified: false, foundIn: V2("chinesisch--shanghai-nacht") },
    ],
    typography: { display: "young-serif", displayWeight: 400, body: "hanken-grotesk", scale: "monumental", labelCase: "uppercase" },
    palette: { background: "#141111", surface: "#1f1a19", text: "#f3ece4", textMuted: "#b9aea3", primary: "#e8574a", onPrimary: "#1a0907", accent: "#c9a24a", line: "#3a302d" },
    shape: { radius: "none" },
    layout: { hero: "immersive-type", menu: "course-led", gallery: "none" },
    motion: { intensity: "expressive" },
  },
  {
    id: "garkueche-feierabend",
    name: "Garküche nach Feierabend",
    mood: "Fast schwarz, ein warmes Orange wie die Lampe über dem Wok, kurze laute Überschriften.",
    cuisines: ["thailaendisch"],
    references: [
      { name: "Smoking Goat", url: "https://www.smokinggoatbar.com", kind: "restaurant", adopted: ["dunkler Grund", "kurze, laute Überschriften"], rejected: ["Merch-Links"], verified: false, foundIn: V2("thailaendisch--streetfood-nacht") },
      { name: "Night + Market", url: "https://www.nightmarketsong.com", kind: "restaurant", adopted: ["Plakat-Hierarchie", "warmes Orange"], rejected: ["knallbunte Mehrfarbigkeit"], verified: false, foundIn: V2("thailaendisch--streetfood-nacht") },
      { name: "Wise Design", url: "https://styles.refero.design/style/c5326639-873a-4257-ad1a-7da9111e9286", kind: "design", adopted: ["laute Überschrift, ruhiger Rest"], rejected: ["Limettengrün als Fläche"], verified: false, foundIn: V2("thailaendisch--streetfood-nacht") },
    ],
    typography: { display: "chivo", displayWeight: 800, body: "chivo", scale: "monumental", labelCase: "uppercase" },
    palette: { background: "#121310", surface: "#1c1d19", text: "#f1efe6", textMuted: "#b4b1a4", primary: "#f08a24", onPrimary: "#1a1208", accent: "#9fbf4a", line: "#34352e" },
    shape: { radius: "soft" },
    layout: { hero: "immersive-type", menu: "card-minimal", gallery: "horizontal-scroll" },
    motion: { intensity: "expressive" },
  },
  {
    id: "strassenkueche-kraeuter",
    name: "Straßenküche mit Kräutern",
    mood: "Heller Grund, Kräutergrün und Preise in ruhigen Ziffern wie auf dem Zettel am Stand.",
    cuisines: ["vietnamesisch"],
    references: [
      { name: "Cây Tre", url: "https://www.caytre.co.uk", kind: "restaurant", adopted: ["helle Flächen", "Kräutergrün"], rejected: ["Gutschein-Banner"], verified: false, foundIn: V2("vietnamesisch--strassenkueche") },
      { name: "Touchy Coffee", url: "https://styles.refero.design/style/6da76890-6e04-452a-834d-ff019e232c2b", kind: "design", adopted: ["handgemachte Anmutung", "eigene Ziffern für Preise und Zeiten"], rejected: ["Pillen-Knöpfe in Extremform"], verified: false, foundIn: V2("vietnamesisch--strassenkueche") },
    ],
    typography: { display: "newsreader", displayWeight: 500, body: "be-vietnam-pro", scale: "compact", labelCase: "normal" },
    palette: { background: "#f6f5ee", surface: "#ffffff", text: "#1d2419", textMuted: "#55604c", primary: "#3f6b24", onPrimary: "#ffffff", accent: "#c2572b", line: "#e2e3d6" },
    shape: { radius: "soft" },
    layout: { hero: "split-editorial", menu: "typographic", gallery: "none" },
    motion: { intensity: "quiet" },
  },
  {
    id: "izakaya-laterne",
    name: "Izakaya unter der Laterne",
    mood: "Dunkles Holz, ein Laternenrot und schmale hohe Schrift nur für wenige Wörter.",
    cuisines: ["japanisch"],
    references: [
      { name: "Bar Goto", url: "https://www.bargoto.com", kind: "restaurant", adopted: ["dunkler Grund", "Rot als Laterne"], rejected: ["Altersabfrage"], verified: false, foundIn: V2("japanisch--izakaya") },
      { name: "Kanada-Ya", url: "https://www.kanada-ya.com", kind: "restaurant", adopted: ["kräftige Rubriken"], rejected: ["App-Download-Banner"], verified: false, foundIn: V2("japanisch--izakaya") },
      { name: "Impossible Foods", url: "https://styles.refero.design/style/04961c7d-8ca6-4e87-ba88-6ad7ffa3b245", kind: "design", adopted: ["Rot auf fast Schwarz", "schmale, große Display-Schrift"], rejected: ["Punk-Anmutung"], verified: false, foundIn: V2("japanisch--izakaya") },
    ],
    typography: { display: "antonio", displayWeight: 700, body: "zen-kaku-gothic-new", scale: "monumental", labelCase: "uppercase" },
    palette: { background: "#16110f", surface: "#211a17", text: "#f2e9df", textMuted: "#bcae9f", primary: "#eadcc6", onPrimary: "#16110f", accent: "#d9483b", line: "#3b302a" },
    shape: { radius: "none" },
    layout: { hero: "immersive-type", menu: "card-minimal", gallery: "none" },
    motion: { intensity: "quiet" },
  },
  {
    id: "gewuerzmarkt-papier",
    name: "Gewürzmarkt auf Papier",
    mood: "Warmes Papier, Safran als Signal und Geschichten neben der Karte, gesetzt wie ein Marktschild.",
    cuisines: ["indisch"],
    references: [
      { name: "Dishoom", url: "https://www.dishoom.com", kind: "restaurant", adopted: ["warmer Papiergrund", "Serife und Versal-Rubriken", "Geschichten neben der Karte"], rejected: ["Illustrations-Überfluss"], verified: false, foundIn: V2("indisch--gewuerzmarkt") },
      { name: "Hoppers", url: "https://www.hopperslondon.com", kind: "restaurant", adopted: ["ein kräftiger Akzent", "direkte Sprache"], rejected: ["Mehrfarb-Illustration"], verified: false, foundIn: V2("indisch--gewuerzmarkt") },
      { name: "Hungry Tiger", url: "https://styles.refero.design/style/47f15da7-8905-45b3-bcab-06a4277c6168", kind: "design", adopted: ["Überschrift als Marktschild"], rejected: ["Graffiti-Texturen"], verified: false, foundIn: V2("indisch--gewuerzmarkt") },
    ],
    typography: { display: "rozha-one", displayWeight: 400, body: "source-serif-4", scale: "editorial", labelCase: "uppercase" },
    palette: { background: "#f5ecdc", surface: "#fcf6ec", text: "#26190f", textMuted: "#5e4b3b", primary: "#9a4a0c", onPrimary: "#ffffff", accent: "#a8701a", line: "#e6d8c1" },
    shape: { radius: "none" },
    layout: { hero: "split-editorial", menu: "course-led", gallery: "full-bleed" },
    motion: { intensity: "editorial" },
  },
  {
    id: "nudelbar-marktstand",
    name: "Nudelbar wie ein Marktstand",
    mood: "Schwarze Schrift auf hellem Grund, ein Pfirsichton als Signal und breite, laute Rubriken.",
    cuisines: ["asiatisch"],
    references: [
      { name: "Momofuku", url: "https://www.momofuku.com", kind: "restaurant", adopted: ["Pfirsich und Orange als Signal", "kräftige Rubriken"], rejected: ["Shop im Vordergrund"], verified: false, foundIn: V2("asiatisch--marktstand") },
      { name: "Little Amps", url: "https://styles.refero.design/style/ca522706-03ed-48cb-acb3-1bb2a22f2eda", kind: "design", adopted: ["gebranntes Orange"], rejected: ["Staubblau"], verified: false, foundIn: V2("asiatisch--marktstand") },
      { name: "Lamanna", url: "https://styles.refero.design/style/057d7c66-76b7-4272-849c-4058543e6799", kind: "design", adopted: ["breite, laute Display-Rubriken"], rejected: ["Mehrfarbigkeit"], verified: false, foundIn: V2("asiatisch--marktstand") },
    ],
    typography: { display: "schibsted-grotesk", displayWeight: 800, body: "schibsted-grotesk", scale: "monumental", labelCase: "uppercase" },
    palette: { background: "#fdf6ef", surface: "#ffffff", text: "#1b1b1b", textMuted: "#555049", primary: "#1b1b1b", onPrimary: "#fdf6ef", accent: "#cf5b33", line: "#ece2d6" },
    shape: { radius: "soft" },
    layout: { hero: "immersive-type", menu: "card-minimal", gallery: "masonry" },
    motion: { intensity: "expressive" },
  },
  {
    id: "roesterei-werkbank",
    name: "Rösterei an der Werkbank",
    mood: "Fast einfarbig, Hafer und Espresso, große Schrift statt Dekoration.",
    cuisines: ["cafe"],
    references: [
      { name: "The Barn", url: "https://www.thebarn.de", kind: "restaurant", adopted: ["fast monochrom", "Produkt als Held"], rejected: ["Shop als Startseite"], verified: false, foundIn: V2("cafe--third-wave") },
      { name: "Five Elephant", url: "https://www.fiveelephant.com", kind: "restaurant", adopted: ["ruhige, helle Flächen"], rejected: [], verified: false, foundIn: V2("cafe--third-wave") },
      { name: "Escape Coffee Company", url: "https://styles.refero.design/style/b5532c58-620a-4d69-8861-35b2b6443956", kind: "design", adopted: ["warmes Off-White", "große Display-Schrift"], rejected: ["Trend-Grotesk"], verified: false, foundIn: V2("cafe--third-wave") },
    ],
    typography: { display: "instrument-serif", displayWeight: 400, body: "instrument-sans", scale: "monumental", labelCase: "normal" },
    palette: { background: "#f3efe8", surface: "#fbf9f5", text: "#1a1714", textMuted: "#5a524a", primary: "#3b2a20", onPrimary: "#f3efe8", accent: "#a47a4e", line: "#e0d9cd" },
    shape: { radius: "round" },
    layout: { hero: "split-editorial", menu: "typographic", gallery: "horizontal-scroll" },
    motion: { intensity: "quiet" },
  },
  {
    id: "kellerstube-kupfer",
    name: "Kellerstube mit Kupfer",
    mood: "Dunkler, warmer Grund wie ein Gewölbe, Kupfer als einziges Licht, Reservierung weit vorn.",
    cuisines: ["deutsch"],
    references: [
      { name: "Ratskeller München", url: "https://www.ratskeller.com", kind: "restaurant", adopted: ["dunkler, warmer Grund", "Kupferakzent"], rejected: ["Pop-up-Banner"], verified: false, foundIn: V2("bayerisch--kellerstube") },
      { name: "Spatenhaus an der Oper", url: "https://www.kuffler.de/de/spatenhaus", kind: "restaurant", adopted: ["Reservierung prominent", "ruhige Serifen-Hierarchie"], rejected: ["Gruppen-Portal-Navigation"], verified: false, foundIn: V2("bayerisch--kellerstube") },
      { name: "Abetterlou", url: "https://styles.refero.design/style/6a5f9438-7ae6-4743-a0bd-f9087d467eff", kind: "design", adopted: ["Cream-Schrift auf Kaffeeschwarz", "bernsteinfarbene Knöpfe"], rejected: ["Grotesk als Überschrift"], verified: false, foundIn: V2("bayerisch--kellerstube") },
    ],
    typography: { display: "libre-caslon-display", displayWeight: 400, body: "libre-franklin", scale: "editorial", labelCase: "uppercase" },
    palette: { background: "#1b1512", surface: "#251d19", text: "#f1e7da", textMuted: "#bfae9c", primary: "#d9955a", onPrimary: "#1b1512", accent: "#b47b45", line: "#3d312a" },
    shape: { radius: "none" },
    layout: { hero: "immersive-type", menu: "course-led", gallery: "masonry" },
    motion: { intensity: "editorial" },
  },
  {
    id: "bistro-leinen",
    name: "Bistro auf Leinen",
    mood: "Leinengrund, Tiefseeblau als Tinte und viel Luft zwischen wenigen Gängen.",
    cuisines: ["international"],
    references: [
      { name: "Lilia", url: "https://www.lilianewyork.com", kind: "restaurant", adopted: ["luftige Abstände", "klare Paarung aus Serife und Grotesk"], rejected: ["Wartelisten-Popup"], verified: false, foundIn: V2("italienisch--costiera") },
      { name: "Miti Navi", url: "https://styles.refero.design/style/887f0c74-c696-4589-82ae-85705ecda919", kind: "design", adopted: ["Leinengrund", "Tiefsee-Blauschwarz als Text"], rejected: ["zu kleine Mono-Schrift"], verified: false, foundIn: V2("italienisch--costiera") },
    ],
    typography: { display: "fraunces", displayWeight: 600, body: "instrument-sans", scale: "editorial", labelCase: "normal" },
    palette: { background: "#f4f1ea", surface: "#fcfbf7", text: "#16222b", textMuted: "#4d5963", primary: "#16222b", onPrimary: "#f4f1ea", accent: "#c96f3b", line: "#dedad0" },
    shape: { radius: "soft" },
    layout: { hero: "split-editorial", menu: "course-led", gallery: "masonry" },
    motion: { intensity: "quiet" },
  },
] as const satisfies readonly DesignDirection[];

export type DirectionId = (typeof DIRECTIONS)[number]["id"];

export function directionById(id: DirectionId): DesignDirection {
  const direction = DIRECTIONS.find((candidate) => candidate.id === id);
  if (!direction) throw new Error(`Unbekannte Design Direction: ${id}`);
  return direction;
}
